### ISSUE TITLE
`net` module error on deployment

### ISSUE THREAD

**Issue by kevmannn** [zeit/now-issues#21]
Getting a strange error from the `net` module when trying to deploy a small express
app - an error not present when executing my `npm start` script directly (or testing etc.):

```
> Deploying ~/Documents/expressiment
net.js:731
      return handle.writeLatin1String(req, data);
                    ^
TypeError: handle.writeLatin1String is not a function
    at createWriteReq (net.js:731:21)
    at Socket._writeGeneric (net.js:701:11)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at Socket.Writable.uncork (_stream_writable.js:243:7)
    at ClientRequest._flushOutput (_http_outgoing.js:666:10)
    at ClientRequest.OutgoingMessage._flush (_http_outgoing.js:640:16)
    at _http_client.js:195:10
    at callSocketMethod (_http_client.js:591:7)
```

**Comment by albinekb** [comment]
Are you using node `v6.4.0`?

I get this when using 6.4.0, but it works in 6.3.1,

Possibly something to do with this (?)
https://github.com/nodejs/node/blame/863952ebadd4909a66bb9da7868bf75bbbe1462d/lib/net.js

This PR: https://github.com/nodejs/node/pull/7111

**In the changelog for 6.4.0**
>[28071a130e] - buffer: introduce latin1 encoding term (Trevor Norris) #7111
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.4.0

**Comment by kevmannn** [comment]
Yep - huh!

Thanks for the info :) I'll use `nvm` for now.
